# Generated by Django 4.2.7 on 2024-01-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='defult_event.jpg', upload_to='event')),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='food'),
        ),
    ]
